### ISSUE TITLE
Pressing "r" in the clipboard no longer autoscales the selected trace.

### ISSUE THREAD

**Issue by dnorgaard-usgs** [usgs/swarm#119]
Reported by Aaron W.

**Comment by dnorgaard-usgs** [comment]
Issue #120 may be related.

On Mon, Jul 24, 2017 at 11:49 AM, Thelen, Weston <wthelen@usgs.gov> wrote:
Hey Diana, 
In using the clipboard in swarm, the hotkeys (R and F) are pretty buggy.  Sometimes they work, sometimes they don't.  I do get this error from the console:

java.lang.NullPointerException

at gov.usgs.net.InternetClient.writeString(InternetClient.java:74)

at gov.usgs.earthworm.WaveServer$2.attempt(WaveServer.java:92)

at gov.usgs.util.Retriable.go(Retriable.java:143)

at gov.usgs.earthworm.WaveServer.getMenuSCNL(WaveServer.java:106)

at gov.usgs.earthworm.WaveServer.getMenuSCNL(WaveServer.java:77)

at gov.usgs.volcanoes.swarm.data.WWSSource.getChannels(WWSSource.java:267)

at gov.usgs.volcanoes.swarm.chooser.DataChooser.openSource(DataChooser.java:760)

at gov.usgs.volcanoes.swarm.chooser.DataChooser.access$1700(DataChooser.java:99)

at gov.usgs.volcanoes.swarm.chooser.DataChooser$DataSourceOpener.construct(DataChooser.java:830)

at gov.usgs.volcanoes.swarm.SwingWorker$2.run(SwingWorker.java:108)

at java.lang.Thread.run(Thread.java:745)

2017-07-24 11:44:11: (WARNING) getMenuSCNL() IOException: null



The error occurs regardless of data source.  To recreate, put at least three waves on the clipboard and try to filter (F).  Or rescale (R). Sometimes the filter will work once I select a different wave on the clipboard. I'm using Swarm 2.7.1 on a mac.



Wes

**Comment by dnorgaard-usgs** [comment]
Unable to replicate in 2.7.1 (version Wes is using) or 2.7.3 (version Aaron reported on), or on Mac or Windows.  Inquiring with Aaron on whether he saw error messages in console.

**Comment by dnorgaard-usgs** [comment]
Will go out in release 2.7.4.
