### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by osop-raspishake** [usgs/swarm#127]
Swarm bonks out every now and again (1 time in 6 loads?) when running on Ubuntu 14.04 and 16.04 systems. Crtl+C, then re-eject does the trick:

branden@branden-AO722:/opt/swarm-2.7.2$ swarm
2017-08-19 12:06:19  INFO - Swarm version/date: Version: 2.7.2 Built: 2017-06-06T16:21:49Z
2017-08-19 12:06:19  INFO - current directory: /opt/swarm-2.7.2
2017-08-19 12:06:19  INFO - user.home: /home/branden
2017-08-19 12:06:19  INFO - Using configuration file: Swarm.config
2017-08-19 12:06:19  INFO - java.version: 1.8.0_111
2017-08-19 12:06:19  INFO - maximum heap size: 823.500 MB
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: No such child: 1
	at java.awt.Container.getComponent(Container.java:334)
	at javax.swing.JLayeredPane.insertIndexForLayer(JLayeredPane.java:670)
	at javax.swing.JLayeredPane.setLayer(JLayeredPane.java:379)
	at javax.swing.JLayeredPane.setPosition(JLayeredPane.java:459)
	at javax.swing.JLayeredPane.moveToFront(JLayeredPane.java:430)
	at javax.swing.JInternalFrame.moveToFront(JInternalFrame.java:1186)
	at javax.swing.JInternalFrame.toFront(JInternalFrame.java:1815)
	at gov.usgs.volcanoes.swarm.Swarm.createUI(Swarm.java:359)
	at gov.usgs.volcanoes.swarm.Swarm.<init>(Swarm.java:107)
	at gov.usgs.volcanoes.swarm.Swarm.main(Swarm.java:1002)
^C^[[A
^C
branden@branden-AO722:/opt/swarm-2.7.2$ swarm
2017-08-19 12:06:26  INFO - Swarm version/date: Version: 2.7.2 Built: 2017-06-06T16:21:49Z
2017-08-19 12:06:27  INFO - current directory: /opt/swarm-2.7.2
2017-08-19 12:06:27  INFO - user.home: /home/branden
2017-08-19 12:06:27  INFO - Using configuration file: Swarm.config
2017-08-19 12:06:27  INFO - java.version: 1.8.0_111
2017-08-19 12:06:27  INFO - maximum heap size: 823.500 MB

**Comment by tparker-usgs** [comment]
What do you see in the Swarm GUI when this occurs? Does the application window appear?

**Comment by osop-raspishake** [comment]
The GUI fails to load.

**Comment by tparker-usgs** [comment]
I'm heading out of town shortly. I'll dig in when I get back late next week.

**Comment by dnorgaard-usgs** [comment]
Hi Branden.  Are you using map packs or WM?  I'm not entirely sure if it matters, but that line # in Swarm.createUI seems to correspond to the map frame being moved to the front.  I wonder if there's an occasional problem reading a layer from (whether from WMS or map packs).  If map packs, maybe you can attach it here.  If WMS, what are your settings?  I have not been able to replicate on Windows 10 or Cent OS 7.  I don't expect there's any change, but please also let us know if you see this in the latest version of Swarm (2.8.5).  Thanks.

**Comment by osop-raspishake** [comment]
buenos días Diana!


This happens from time-to-time when opening Swarm. Hard to say how often, but it is pretty common. I usually just Crtl+C out and re-execute the program (and it usually works on the second go around). 

It actually just happened again:

branden@branden:/opt$ swarm
2018-07-24 08:09:01  INFO - Swarm version/date: Version: 2.7.0 Built: 2017-05-10T17:31:25Z
2018-07-24 08:09:01  INFO - current directory: /opt/swarm-2.7.0
2018-07-24 08:09:01  INFO - user.home: /home/branden
2018-07-24 08:09:01  INFO - Using configuration file: Swarm.config
2018-07-24 08:09:01  INFO - java.version: 1.8.0_171
2018-07-24 08:09:01  INFO - maximum heap size: 3545.000 MB
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: No such child: 1
	at java.awt.Container.getComponent(Container.java:335)
	at javax.swing.JLayeredPane.insertIndexForLayer(JLayeredPane.java:670)
	at javax.swing.JLayeredPane.setLayer(JLayeredPane.java:379)
	at javax.swing.JLayeredPane.setPosition(JLayeredPane.java:459)
	at javax.swing.JLayeredPane.moveToFront(JLayeredPane.java:430)
	at javax.swing.JInternalFrame.moveToFront(JInternalFrame.java:1186)
	at javax.swing.JInternalFrame.toFront(JInternalFrame.java:1815)
	at gov.usgs.volcanoes.swarm.Swarm.createUI(Swarm.java:353)
	at gov.usgs.volcanoes.swarm.Swarm.<init>(Swarm.java:107)
	at gov.usgs.volcanoes.swarm.Swarm.main(Swarm.java:963)


You will notice that, unfortunately, I am not running the latest version. I have a lot of computers and I move around a lot so they are not always up to date. 

I am not sure what the map packs or WM(S) are. What I can say is that I run Swarm with no modifications to the mapdata/ directory. I just download Swarm from the USGS site, unpack, copy in my Swarm.config file from a previous version of Swarm and execute. 

Attached are the config files in my Swarm directory. Maybe one will provide an insight for you. 

If I can help in any other way, please let me know. 

[config_files.zip](https://github.com/usgs/swarm/files/2223816/config_files.zip)

Branden

**Comment by dnorgaard-usgs** [comment]
I confirmed that where it seems to be failing is the line where it tries to bring the map frame to front:

```
final MapFrame mapFrame = MapFrame.getInstance();
    SwarmInternalFrames.add(mapFrame);
    mapFrame.setVisible(config.mapVisible);
    if (Swarm.config.mapMaximized) {
      try {
        mapFrame.setMaximum(true);
      } catch (final Exception e) {
      }
    }

    mapFrame.toFront();

```
There was a change made about 10 months ago (probably in 2.8.1 or 2.8.2) to following:

```
    final MapFrame mapFrame = MapFrame.getInstance();
    SwarmInternalFrames.add(mapFrame);
    mapFrame.setVisible(config.mapVisible);
    if (Swarm.config.mapMaximized) {
      try {
        mapFrame.setMaximum(true);
      } catch (final Exception e) {
        //
      }
    }
    if (applicationFrame.isVisible()) {
      mapFrame.toFront();
    }
```

This change may have been to address this problem.  Please try the latest version of Swarm to see if you still get the error.  

Btw, you use the map packs, which is fine.  You might be interested in trying to WMS as it gives better maps in some places.  Go to File->Options and select Use WMS under Maps.  

![image](https://user-images.githubusercontent.com/25251719/43154346-ea5086b0-8f28-11e8-9018-cb962536cc4d.png)

**Comment by osop-raspishake** [comment]
OK, I would say go ahead and close this issue then. I will move to the latest and greatest code on all my systems and submit a new issue if I see it again.
