### ISSUE TITLE
Java heap space error when retrieving  an 'old' helicorder from FDSN

### ISSUE THREAD

**Issue by rumachan** [usgs/swarm#182]
GeoNet (NZ) now routinely uses FDSN web servers for our data source for Swarm. If I try to retrieve an 'old' helicorder, something of a few years ago, for instance, then Swarm always has a Java heap space error. This problem does not arise if I request 'current' data or 'recent' data.

If I request 'old' data from the FDSN web server by some other means, such as the FDSN client in ObsPy, I have not issues. I take that to mean our FDSN web server is working fine.

Here is an example of the error
2018-02-08 06:42:25  INFO - Swarm version/date: Version: 2.8.2 Built: 2017-11-09T20:53:04Z
2018-02-08 06:42:25  INFO - current directory: /home/ruma/source/swarm-2.8.2
2018-02-08 06:42:25  INFO - user.home: /home/ruma
2018-02-08 06:42:25  INFO - Using configuration file: Swarm.config
2018-02-08 06:42:25  INFO - java.version: 1.8.0_151
2018-02-08 06:42:25  INFO - maximum heap size: 3547.000 MB
java.lang.OutOfMemoryError: Java heap space
	at edu.iris.dmc.seedcodec.Steim2.decode(Steim2.java:55)
	at edu.iris.dmc.seedcodec.Codec.decompress(Codec.java:120)
	at gov.usgs.volcanoes.swarm.data.seedLink.SeedUtils.createWave(SeedUtils.java:50)
	at gov.usgs.volcanoes.swarm.data.fdsnWs.AbstractDataRecordClient.addWaves(AbstractDataRecordClient.java:50)
	at gov.usgs.volcanoes.swarm.data.fdsnWs.WebServicesClient$3.processRecord(WebServicesClient.java:207)
	at gov.usgs.volcanoes.swarm.data.fdsnWs.DataSelectReader.read(DataSelectReader.java:210)
	at gov.usgs.volcanoes.swarm.data.fdsnWs.WebServicesClient.getRawData(WebServicesClient.java:217)
	at gov.usgs.volcanoes.swarm.data.fdsnWs.WebServicesSource.getWave(WebServicesSource.java:234)
	at gov.usgs.volcanoes.swarm.data.fdsnWs.WebServicesSource.getHelicorder(WebServicesSource.java:210)
	at gov.usgs.volcanoes.swarm.heli.HelicorderViewerFrame$23.construct(HelicorderViewerFrame.java:781)
	at gov.usgs.volcanoes.swarm.SwingWorker$2.run(SwingWorker.java:111)
	at java.lang.Thread.run(Thread.java:748)
getHelicorder() Error: Java heap space

**Comment by rumachan** [comment]
Hi Diana,

Yes, I just reproduced  the problem. I included my command line as well as the Swarm screen so you can see as much as I can.

The FDSN server we use for data older than 8 days is optimised for data completeness, rather rhan retrieval speed. Is there any reason that might contribute to the issue? There is no issue with our FDSN server used for data up to 8 days old, which is optimised for speed.


![screenshot from 2018-12-05 14-27-30](https://user-images.githubusercontent.com/10933207/49484095-9ef04a80-f89a-11e8-99b3-c716b66684c0.png)

alertClip=false

alertClipTimeout=5

chooserDividerLocation=242

chooserVisible=true

clipboardMaximized=true

clipboardSizeX=1411

clipboardSizeY=661

clipboardVisible=false

clipboardX=794

clipboardY=369

durationA=1.86

durationB=-0.85

durationEnabled=false

fdsnDataselectURL=http://beta-service-nrt.geonet.org.nz/fdsnws/dataselect/1/query

fdsnStationURL=http://beta-service-nrt.geonet.org.nz/fdsnws/station/1/query

hypocenterSource=NONE

kiosk=false

lastPath=/home/sherburn/Desktop

mapHeight=510

mapLatitude=-39.181227500000006

mapLineColor=0

mapLineWidth=2

mapLongitude=175.6013785

mapMaximized=true

mapPath=mapdata

mapScale=100.62837488300208

mapVisible=false

mapWidth=600

mapX=0

mapY=0

nearestDividerLocation=718

pVelocity=6.0

saveConfig=true

server=GeoNet FDSN;wsc:NZ|MAVZ,FWVZ,TRVZ,WHVZ,TOVZ,IVVZ,COVZ,TMVZ,KRVZ,OTVZ,WTVZ,NGZ,NTVZ,WIZ,WSRZ,GLKZ,RIZ,NGZ,NNVZ|10,30|EH?,HH?,HDF,HDH|3600|0|http://service.geonet.org.nz/fdsnws/dataselect/1/query|http://service.geonet.org.nz/fdsnws/station/1/query
server=GeoNet FDSN NRT Beta;wsc:NZ|MAVZ,FWVZ,TRVZ,WHVZ,TOVZ,IVVZ,COVZ,TMVZ,KRVZ,OTVZ,WTVZ,NGZ,NTVZ,WIZ,WSRZ,GLKZ,RIZ,NGZ,NNVZ,KHEZ,NEZ,PREZ,PKE,NBEZ,DREZ,NMEZ,MHEZ,LREZ|10,11,30,31,32|EH?,HH?,HDF,HDH|3600|0|http://beta-service-nrt.geonet.org.nz/fdsnws/dataselect/1/query|http://beta-service-nrt.geonet.org.nz/fdsnws/station/1/query

showClip=true

span=24

specificTimeZone=UTC

timeChunk=30

useInstrumentTimeZone=true

useLargeCursor=false

useLocalTimeZone=true

useWMS=false

userTimes=20180123,20171030

velocityRatio=1.73

windowMaximized=true

windowSizeX=1920

windowSizeY=1032

windowX=0

windowY=0

wmsLayer=global_mosaic

wmsServer=http://wms.jpl.nasa.gov/wms.cgi

wmsStyles=visual

**Comment by dnorgaard-usgs** [comment]
Hi,

My only guess is that the server optimized for completeness is returning more data each retrieval.  Have you tried adjusting the gulp size and delay?  Gulp size setting determines how much past data to retrieve at a time.  It is currently set to 60.  You might want to try reducing that.  Gulp delay determines how much time passes between data retrieval.  Increasing this (try 1 second) may help.

![image](https://user-images.githubusercontent.com/25251719/49750414-a8453280-fc5f-11e8-90f4-a45bb92c3790.png)

Also, Swarm has only been tested on Java 8.  I don't reckon running on a newer version of Java should cause any issues, but can't say for sure.  If you have access to Java 8 you might want to try that too.

Let me know how it goes.

Diana

**Comment by rumachan** [comment]
Hi Diana,
Thank you for those suggestions.
I have tried several combinations without any effect:
- On my Linux system (which I usually use, Java ver 10) I tried to reduce Gulp size to 20 mins and increase Gulp delay to 1 sec.
- On a Windows system (java ver 8) I tried the same settings
- On Linux, a Gulp size of 10 mins and Gulp delay of 1 sec, I did not get an error, but after 5+ mins no waveform on my helicorder plot either.

If I don't try to get data from so far back in time (2018-11-01 instead of 2018-01-01 which I was trying), I am getting data, despite the error 'getHelicorder() Error: Java heap space'. But I can't get data from, for example, 2018-06-01. I can access those data using, for example, ObsPy. What is it about the way Swarm accesses data from FDSN that is causing an issue if data retrieval is 'slow'?

I'm surprised you couldn't access our FDSN servers as they are open. Can you try the near real-time server? 
http://service-nrt.geonet.org.nz/fdsnws/dataselect/1/query
http://service-nrt.geonet.org.nz/fdsnws/station/1/query

Thanks again,

Steven Sherburn

**Comment by dnorgaard-usgs** [comment]
Hi.  If I configured the data source manually it seems I can access it. Maybe I had a bad cut and paste of swarm config.  I can also access beta.  However, in both cases, if I try to access June or November data, I get something like:

2018-12-10 02:11:02  WARN - could not get web service raw data (WIZ HHZ NZ 10): Did not get an OK repsonse code (code=204, url=http://beta-service-nrt.geonet.org.nz/fdsnws/dataselect/1/query?net=NZ&sta=WIZ&loc=10&cha=HHZ&start=2018-06-01T14:31:40&end=2018-06-01T15:31:40"

Upon digging further the return code and message indicates there is no content for that time period. For both urls anything beyond 8 days does not return data for me. I confirmed in browser this is the case. This does not sound like what you are experiencing though.  It sounds like you can get data past 8 days but eventually get an out of memory error?  

How are you going back in time?  Through the left arrows up top of helicorder?  Or through Helicorder View Settings?  I am trying the latter.  

![image](https://user-images.githubusercontent.com/25251719/49766434-25859d00-fc8a-11e8-9d5a-8299be5a01a2.png)

**Comment by rumachan** [comment]
Sorry I might not have made the distinction between the two FDSN servers clear enough.
The NRT server, service-nrt.geonet.org.nz, or its beta version, which still seems to be running, beta-service-nrt.geonet.org.nz, **only** contain data for the last 8 days.
The other server, service.geonet.org.nz, **only** contains data older than 7 days. So there is about a 1 day overlap.
The intention is that the NRT server focuses on providing quick access to data, but does not worry about completeness. The other server's focus is completeness and accuracy.
If you ask service-nrt (or beta-service-nrt) for data from June you'll get nothing, so Swarm works as it should.

I am having no issues with Swarm retrieving data from service-nrt.geonet.org.nz, only from service.geonet.org.nz.

To go back in time I:
- select the stream I want to view
- enter the date in the box Open to:
- click the helicorder icon
![screenshot from 2018-12-12 08-27-36](https://user-images.githubusercontent.com/10933207/49824900-0270ff80-fde8-11e8-85ee-597fe0f346fe.png)
I think this is effectively the same as you are doing?

**Comment by dnorgaard-usgs** [comment]
I was able to reproduce the problem.  I believe I have a fix. Can you confirm?  2.8.7-snapshot version is attached.

[swarm-2.8.7-SNAPSHOT-bin.zip](https://github.com/usgs/swarm/files/2673256/swarm-2.8.7-SNAPSHOT-bin.zip)

**Comment by rumachan** [comment]
Yes, that works brilliantly. Checked with both service and service-nrt. I went back in one case to 2012, and fine. I also tried going back with << in helicorder view from quite old data and that was fine, and quick too. The retrieval speed with service for our FDSN server is little different from our service-nrt.
No heap space messages at all.

You plan to add this fix to the next release, but the look of it?

**Comment by rumachan** [comment]
Great, thank you very much!
