### ISSUE TITLE
WMS map not working for some

### ISSUE THREAD

**Issue by dnorgaard-usgs** [usgs/swarm#228]
On Thu, Aug 9, 2018 at 1:48 PM, Shiro, Brian wrote:
Hi Diana,

That URL resolves in a browser to show a map as expected.

I have previously tried toggling different map layers such as Shaded to Topo with no luck.

The console output upon swarm start is shown below.

HVO-Swarm bshiro$ ./swarm.sh
```

2018-08-09 10:47:09  INFO - Swarm version/date: Version: 2.8.6 Built: 2018-08-09T17:30:29Z

2018-08-09 10:47:09  INFO - current directory: /Applications/Seismic/HVO-Swarm

2018-08-09 10:47:09  INFO - user.home: /Users/bshiro

2018-08-09 10:47:09  INFO - Using configuration file: Swarm.config

2018-08-09 10:47:09  INFO - java.version: 1.8.0_131

2018-08-09 10:47:09  INFO - maximum heap size: 3641.000 MB

2018-08-09 10:47:11  INFO - Retrieving hypocenters

2018-08-09 10:47:11  INFO - https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WMSServer?&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=0&STYLES=&WIDTH=815&HEIGHT=119&FORMAT=image/jpeg&EXCEPTIONS=application/vnd.ogc.se_xml&SRS=EPSG:4326&BBOX=-155.30074,19.40166,-155.22066,19.41073

2018-08-09 10:47:13  WARN - Unable to retrieve QuakeML.

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)

	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)

	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)

	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)

	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)

	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)

	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)

	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)

	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)

	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)

	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)

	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)

	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)

	at java.net.URL.openStream(URL.java:1045)

	at gov.usgs.volcanoes.core.quakeml.QuakemlSource.updateQuakeml(QuakemlSource.java:73)

	at gov.usgs.volcanoes.core.quakeml.QuakemlSource.access$000(QuakemlSource.java:19)

	at gov.usgs.volcanoes.core.quakeml.QuakemlSource$1.run(QuakemlSource.java:56)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at java.lang.Thread.run(Thread.java:748)

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)

	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)

	at sun.security.validator.Validator.validate(Validator.java:260)

	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)

	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)

	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)

	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)

	... 23 more

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)

	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)

	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)

	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)

	... 29 more

2018-08-09 10:47:14 ERROR - Exception during map creation. {}

java.lang.NullPointerException

	at gov.usgs.volcanoes.core.legacy.plot.map.WMSGeoImageSet$1.attempt(WMSGeoImageSet.java:182)

	at gov.usgs.volcanoes.core.util.Retriable.go(Retriable.java:145)

	at gov.usgs.volcanoes.core.legacy.plot.map.WMSGeoImageSet.getCompositeImage(WMSGeoImageSet.java:196)

	at gov.usgs.volcanoes.core.legacy.plot.map.GeoImageSet.getMapBackground(GeoImageSet.java:419)

	at gov.usgs.volcanoes.swarm.map.MapPanel.updateMapRenderer(MapPanel.java:774)

	at gov.usgs.volcanoes.swarm.map.MapPanel.access$500(MapPanel.java:82)

	at gov.usgs.volcanoes.swarm.map.MapPanel$5.construct(MapPanel.java:971)

	at gov.usgs.volcanoes.swarm.SwingWorker$2.run(SwingWorker.java:111)

	at java.lang.Thread.run(Thread.java:748)

2018-08-09 10:47:16 ERROR - getCurrentTime(): unsuccessful after 4 attempts.

2018-08-09 10:47:18 ERROR - getCurrentTime(): unsuccessful after 4 attempts.


```

On Thu, Aug 9, 2018 at 10:32 AM, Norgaard, Diana wrote:
Hi Brian,

I was able to get a map with your configurations.

What do you get when you put this in your browser?  Just checking that nothing is blocking access from within HVO's network (unlikely).

https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WMSServer?&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=0&STYLES=&WIDTH=1679&HEIGHT=959&FORMAT=image/jpeg&EXCEPTIONS=application/vnd.ogc.se_xml&SRS=EPSG:4326&BBOX=-155.34288,19.36266,-155.17852,19.44972

Can you also send me a screenshot of your cmd Window upon start up? I want to confirm you're pulling up the above URL also, e.g:

I would suggest going to File->Options, and try selecting one of the other USGS maps (e.g. Shaded Relief) and hit OK.  If this works, then select Topo again to see if that helps.

Diana

ps. Thanks for the feedback and suggestion on the document.  I will package it up into the zip file on next release.

On Thu, Aug 9, 2018 at 1:21 PM, Shiro, Brian wrote:
Diana,

I use the default WMS right now.  I haven't tried map packs.  Maybe I should use that for better performance, especially over VPN.

Swarm.config is attached.

By the way, I wanted to compliment you on the excellent PDF manual.  I suggest bundling it in the zip file for user convenience.

Thanks,
Brian

On Thu, Aug 9, 2018 at 10:17 AM, Norgaard, Diana wrote:
do you use map packs or WMS?  (or you can send me your Swarm.config and I can take a look).  Sorry if you mentioned this before.  Somehow it didn't make it to the list of issues in Swarm.  I do have a few others you suggested still on the list: https://github.com/usgs/swarm/issues (192-194).

On Thu, Aug 9, 2018 at 1:14 PM, Shiro, Brian  wrote:
This is great, thanks.  I like the RSAM features!

The map still doesn't work for me, though.  It just produces a blank gray window and never shows anything.  I've had to use version 2.7.4 as a result since the map still works in that version.

Brian

On Thu, Aug 9, 2018 at 7:44 AM, Norgaard, Diana wrote:
Hi,

Swarm 2.8.6 is now available.  It is mostly bug fixes and minor enhancements:

  * Add RSAM value of selected wave panel period to status bar (#103)
  * Addition of map option to hide station icons (#124)
  * Fix issue with streaming failing on loss of data (#142)
  * Fix issue using WWS instrument time zone (#201)
  * Fix multiple event dialog showing up under Window menu (#216)
  * Fix problem parsing server response from CWB (#221)
  * Support height metadata for FDSN data source (#222)
  * Position real-time wave viewer and RSAM viewer when opening layout (#224)
  * Updated WWS Client to 1.3.5

Please download from https://volcanoes.usgs.gov/software/swarm/documentation.php at your convenience.

thanks,
Diana

**Comment by dnorgaard-usgs** [comment]
This seemed to be an issue related to missing cacerts when on DOI network.  Bill troubleshooted and provided following fix to Brian:

1. Copy my java keystore into the swarm directory so that I wasn't editing the default keystore.

sudo cp $(/usr/libexec/java_home)/jre/lib/security/cacerts .

2. Add the DOI cert to the local keystore:

sudo keytool -importcert -file DOIRootCA2.crt -alias doi -keystore cacerts -storepass changeit

3. Force java to use this specific keystore. To do so, edit swarm.sh and add:

-Djavax.net.ssl.trustStore=cacerts

If you want to debug SSL to verify that it's using the correct keystore, you can also add -Djavax.net.debug=ssl. Note that doing so dramatically increases the output, so you'd want to pipe that to a file somewhere. The keystore being used will be listed near the top (see bolded output below):

2018-08-10 10:05:56  INFO - Swarm version/date: Version: 2.8.6 Built: 2018-08-09T17:30:29Z

2018-08-10 10:05:56  INFO - current directory: /Users/wtollett/Downloads/swarm-2.8.6

2018-08-10 10:05:56  INFO - user.home: /Users/wtollett

2018-08-10 10:05:56  INFO - Using configuration file: Swarm.config

2018-08-10 10:05:56  INFO - java.version: 1.8.0_171

2018-08-10 10:05:56  INFO - maximum heap size: 3641.000 MB

2018-08-10 10:05:57  INFO - Retrieving hypocenters

2018-08-10 10:05:58  INFO - https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WMSServer?&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=0&STYLES=&WIDTH=1799&HEIGHT=744&FORMAT=image/jpeg&EXCEPTIONS=application/vnd.ogc.se_xml&SRS=EPSG:4326&BBOX=-179.99982,-62.02899,179.99982,62.02899

trustStore is: /Users/wtollett/Downloads/swarm-2.8.6/cacerts
