### ISSUE TITLE
Unable to read mseed file with encoding type float32(4)

### ISSUE THREAD

**Issue by dnorgaard-usgs** [usgs/swarm#238]
In gov.usgs.volcanoes.core.data.file.SeedDataFile.extract(), it is trying to read the decompressed data as int but the encoding type is float so the returned values are null.

On 10/16/2018 4:39 PM, Wech, Aaron wrote:
> Hi Diana,
>
> I'm trying to open a miniseed file in swarm, but it doesn't seem to be working. I encountered the issue on version 2.8.5, but upgrading to 2.8.6 didn't fix it either. Here's the v2.8.6 console message:
> java.lang.NullPointerException
> 	at gov.usgs.volcanoes.core.data.file.SeedDataFile.extract(SeedDataFile.java:183)
> 	at gov.usgs.volcanoes.core.data.file.SeedDataFile.read(SeedDataFile.java:119)
> 	at gov.usgs.volcanoes.swarm.data.FileDataSource$1.construct(FileDataSource.java:155)
> 	at gov.usgs.volcanoes.swarm.SwingWorker$2.run(SwingWorker.java:111)
> 	at java.lang.Thread.run(Thread.java:745)
>
> I've attached the mseed file in case it is the culprit.
>
> Thanks,
> Aaron
>
> -- 
[test_event.zip](https://github.com/usgs/swarm/files/2485394/test_event.zip)

**Comment by dnorgaard-usgs** [comment]
It appears some of the downstream code that uses the data (e.g. Wave object)  also require int values for the samples.  Likely we will not fix this and have users convert their source data to integer type for use with Swarm.

**Comment by dnorgaard-usgs** [comment]
Updated User Guide with info on encoding requirements for SEED files.
