### ISSUE TITLE
Unable to close swarm window using File > Exit

### ISSUE THREAD

**Issue by iannesbitt** [usgs/swarm#240]
Recently I've been unable to close my Swarm GUI window using either File > Exit or the X button on the top bar of the window. I'm using Arch Linux and I start Swarm from the terminal. It works just fine on Ubuntu, so perhaps this is an upstream bug. However no other java application on Arch has this problem and I'm not familiar enough with java to know where the issue lies. I've un- and reinstalled Java a couple times (I tried v.7, v.8, and v.10) but have seen no change.

The console output I get is:
```
2018-11-26 04:04:55  INFO - Swarm version/date: Version: 2.8.6 Built: 2018-08-09T17:30:29Z
2018-11-26 04:04:55  INFO - current directory: /home/user/bin/swarm-2.8.6
2018-11-26 04:04:55  INFO - user.home: /home/user
2018-11-26 04:04:55  INFO - Using configuration file: Swarm.config
2018-11-26 04:04:55  INFO - java.version: 10.0.2
2018-11-26 04:04:55  INFO - maximum heap size: 7.832 GB
2018-11-26 04:04:56  INFO - loading MapPack: mapdata/augustine/MapPack.txt
2018-11-26 04:04:56  INFO - loading MapPack: mapdata/nasa_240m_D2/MapPack.txt
2018-11-26 04:04:56  INFO - loading MapPack: mapdata/nasa_2k/MapPack.txt
2018-11-26 04:04:56  INFO - loading MapPack: mapdata/world/MapPack.txt
2018-11-26 04:04:56  INFO - loading MapPack: mapdata/nasa_240m_A1/MapPack.txt
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jgoodies.common.internal.RenderingUtils (file:/home/user/bin/swarm-2.8.6/lib/swarm.jar) to method sun.swing.SwingUtilities2.drawStringUnderlineCharAt(javax.swing.JComponent,java.awt.Graphics,java.lang.String,int,int,int)
WARNING: Please consider reporting this to the maintainers of com.jgoodies.common.internal.RenderingUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
	at gov.usgs.volcanoes.swarm.data.WaveServerSource.toConfigString(WaveServerSource.java:73)
	at gov.usgs.volcanoes.swarm.SwarmConfig.toConfigFile(SwarmConfig.java:583)
	at gov.usgs.volcanoes.swarm.Swarm.closeApp(Swarm.java:525)
	at gov.usgs.volcanoes.swarm.SwarmMenu$7.actionPerformed(SwarmMenu.java:235)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:980)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1024)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at gov.usgs.volcanoes.core.ui.GlobalKeyManager.dispatchEvent(GlobalKeyManager.java:82)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by iannesbitt** [comment]
Something similar is happening when I click the "Edit data source" button:

```
2018-11-27 02:03:18  INFO - Swarm version/date: Version: 2.8.6 Built: 2018-08-09T17:30:29Z
2018-11-27 02:03:18  INFO - current directory: /home/iannesbitt/bin/swarm-2.8.6
2018-11-27 02:03:18  INFO - user.home: /home/iannesbitt
2018-11-27 02:03:18  INFO - Using configuration file: Swarm.config
2018-11-27 02:03:18  INFO - java.version: 10.0.2
2018-11-27 02:03:18  INFO - maximum heap size: 7.832 GB
2018-11-27 02:03:19  INFO - loading MapPack: mapdata/augustine/MapPack.txt
2018-11-27 02:03:19  INFO - loading MapPack: mapdata/nasa_240m_D2/MapPack.txt
2018-11-27 02:03:19  INFO - loading MapPack: mapdata/nasa_2k/MapPack.txt
2018-11-27 02:03:19  INFO - loading MapPack: mapdata/world/MapPack.txt
2018-11-27 02:03:19  INFO - loading MapPack: mapdata/nasa_240m_A1/MapPack.txt
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
	at gov.usgs.volcanoes.swarm.data.WaveServerSource.toConfigString(WaveServerSource.java:73)
	at gov.usgs.volcanoes.swarm.chooser.DataChooser$2.actionPerformed(DataChooser.java:336)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at gov.usgs.volcanoes.core.ui.GlobalKeyManager.dispatchEvent(GlobalKeyManager.java:82)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by dnorgaard-usgs** [comment]
Hi.  Can you please send me your configuration file where your data source is configured?  Based on the line number of the error, it appears there is some problem parsing the timeZone for the data source.  I'm not quite sure why this would be a problem on Arch Linux and not on Ubuntu though.  Can  you also see if the attached version of Swarm fixes it?

[swarm-2.8.7-SNAPSHOT-bin.zip](https://github.com/usgs/swarm/files/2627625/swarm-2.8.7-SNAPSHOT-bin.zip)

**Comment by dnorgaard-usgs** [comment]
Which data source causes the exception when you try to edit it?
