### ISSUE TITLE
Bugs Swarm v3.0.2

### ISSUE THREAD

**Issue by Thor0001** [usgs/swarm#314]
-no open layouts with Helicorder and no save layout with Helicorder.
Detail error "cmd" :
Exception in thread "Thread-4" java.lang.NumberFormatException: For input string: "9803.0"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at gov.usgs.volcanoes.swarm.heli.HelicorderViewerSettings.set(HelicorderViewerSettings.java:85)
        at gov.usgs.volcanoes.swarm.heli.HelicorderViewerFrame.<init>(HelicorderViewerFrame.java:164)
        at gov.usgs.volcanoes.swarm.SwarmLayout.processHelicorders(SwarmLayout.java:220)
        at gov.usgs.volcanoes.swarm.SwarmLayout.access$300(SwarmLayout.java:37)
        at gov.usgs.volcanoes.swarm.SwarmLayout$1.construct(SwarmLayout.java:119)
        at gov.usgs.volcanoes.swarm.SwingWorker$2.run(SwingWorker.java:111)
        at java.lang.Thread.run(Unknown Source)

**Comment by dnorgaard-usgs** [comment]
Duplicate to #312

**Comment by dnorgaard-usgs** [comment]
Should have a fix out this week but if you need layouts in meantime, please use 3.0.0.

**Comment by dnorgaard-usgs** [comment]
Fixed in 3.1.0: https://volcanoes.usgs.gov/software/swarm/download.shtml

Note, code base is now maintained in https://code.usgs.gov/vsc/swarm as of today.  Please report any new issues there.
