### ISSUE TITLE
Can't go back to wave view after scaling Y axis in spectrogram

### ISSUE THREAD

**Issue by dnorgaard-usgs** [usgs/swarm#320]
In the wave panel view, if you switch to spectrogram, you can scale the Y axis by using '[' and ']'. After doing so, however, you can't switch back to waveform view. The terminal throws an error:

Exception in thread "Thread-38" java.lang.NegativeArraySizeException
	at gov.usgs.volcanoes.core.legacy.plot.decorate.SmartTick.autoTick(SmartTick.java:98)
	at gov.usgs.volcanoes.core.legacy.plot.decorate.SmartTick.autoTick(SmartTick.java:31)
	at gov.usgs.volcanoes.core.legacy.plot.decorate.DefaultFrameDecorator.createYAxis(DefaultFrameDecorator.java:316)
	at gov.usgs.volcanoes.core.legacy.plot.decorate.DefaultFrameDecorator.decorate(DefaultFrameDecorator.java:426)
	at gov.usgs.volcanoes.core.legacy.plot.render.wave.SliceWaveRenderer.update(SliceWaveRenderer.java:309)
	at gov.usgs.volcanoes.swarm.wave.WaveViewPanel.plotWave(WaveViewPanel.java:1241)
	at gov.usgs.volcanoes.swarm.wave.WaveViewPanel.constructPlot(WaveViewPanel.java:1149)
	at gov.usgs.volcanoes.swarm.wave.WaveViewPanel.access$0(WaveViewPanel.java:1132)
	at gov.usgs.volcanoes.swarm.wave.WaveViewPanel$5.run(WaveViewPanel.java:798)
	at gov.usgs.volcanoes.swarm.wave.WaveViewPanel$6.construct(WaveViewPanel.java:807)
	at gov.usgs.volcanoes.swarm.SwingWorker$2.run(SwingWorker.java:113)

**Comment by dnorgaard-usgs** [comment]
fixed
