### ISSUE TITLE
Swarm doesn't start - I messed up somehow

### ISSUE THREAD

**Issue by dormant** [usgs/swarm#326]
I have been editing SwarmMetadata.config and now swarm will not start. This is on MacOS Big Sur.

I must have messed up, but I can't work out where. I tried using the unedited backup of SwarmMetadata.config, but swarm still doesn't start.

Any advice would be welcome.

Here's the output:

2021-02-08 03:41:40  INFO - Swarm version/date: Version: 3.2.0 Built: 2020-09-30T22:28:44Z
2021-02-08 03:41:40  INFO - current directory: /Users/stewart/src/swarm/swarm-3.2.0-mvo
2021-02-08 03:41:40  INFO - user.home: /Users/stewart
2021-02-08 03:41:40  INFO - Using configuration file: Swarm.config
2021-02-08 03:41:40  INFO - Using metadata configuration file: SwarmMetadata.config
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 96
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
	at java.base/java.lang.String.substring(String.java:1903)
	at gov.usgs.volcanoes.core.configfile.ConfigFile.readConfigFile(ConfigFile.java:510)
	at gov.usgs.volcanoes.core.configfile.ConfigFile.readConfigFile(ConfigFile.java:570)
	at gov.usgs.volcanoes.core.configfile.ConfigFile.readConfigFile(ConfigFile.java:559)
	at gov.usgs.volcanoes.core.configfile.ConfigFile.<init>(ConfigFile.java:100)
	at gov.usgs.volcanoes.swarm.SwarmLayout.createSwarmLayout(SwarmLayout.java:52)
	at gov.usgs.volcanoes.swarm.SwarmConfig.loadLayouts(SwarmConfig.java:261)
	at gov.usgs.volcanoes.swarm.SwarmConfig.createConfig(SwarmConfig.java:220)
	at gov.usgs.volcanoes.swarm.Swarm.<init>(Swarm.java:101)
	at gov.usgs.volcanoes.swarm.Swarm.main(Swarm.java:1130)
2021-02-08 03:41:40  INFO - java.version: 15
2021-02-08 03:41:40  INFO - maximum heap size: 4096.000 MB
2021-02-08 03:41:41  INFO - loading MapPack: mapdata/mvo_aster/MapPack.txt
2021-02-08 03:41:41  INFO - loading MapPack: mapdata/smu_sentinel/MapPack.txt
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "gov.usgs.volcanoes.swarm.SwarmLayout.process()" because "sl" is null
	at gov.usgs.volcanoes.swarm.Swarm.createUi(Swarm.java:372)
	at gov.usgs.volcanoes.swarm.Swarm.<init>(Swarm.java:108)
	at gov.usgs.volcanoes.swarm.Swarm.main(Swarm.java:1130)

**Comment by dnorgaard-usgs** [comment]
Can you please attach your SwarmMetadata.config so I can take a look?

**Comment by dormant** [comment]
attached


--
Roderick Stewart
Research Fellow (Volcano-Seismology), Montserrat Volcano Observatory
www.mvo.ms <http://www.mvo.ms/>
email: rod@mvo.ms <mailto:rod@mvo.ms>, roderick.stewart@gmail.com <mailto:roderick.stewart@gmail.com>, rstewart@my.uwi.edu <mailto:rstewart@my.uwi.edu>

phone: (+1-664) 491-5647
fax: (+1-664) 491-2423
direct line: (+1-664) 491-5726
mobile: (+1-664) 495-0743
home: (+1-664) 491-3139
roaming: +44 7452 023889
trinidad: +1 (868) 780-4296‬

**Comment by dnorgaard-usgs** [comment]
The problem was the layout used in Swarm config did not exist.  I added code to handle such errors in the future.
