### ISSUE TITLE
Error saving config on exit

### ISSUE THREAD

**Issue by tparker-usgs** [usgs/swarm#82]
Wes reports Swarm hangs on close running on windows.

 "InvalidPathException...illegal char at index 3...".\C:\home\glowworm\swarm.config".

**Comment by dnorgaard-usgs** [comment]
I was able to replicate this.  Full stack trace:

Exception in thread "AWT-EventQueue-1" java.nio.file.InvalidPathException: Illegal char <:> at index 3: .\C:\Users\Diana\Swarm.config
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at gov.usgs.volcanoes.core.configfile.ConfigFile.writeToFile(ConfigFile.java:624)
        at gov.usgs.volcanoes.swarm.Swarm.closeApp(Swarm.java:500)
        at gov.usgs.volcanoes.swarm.Swarm$14.windowClosing(Swarm.java:279)
        at java.awt.Window.processWindowEvent(Unknown Source)
        at javax.swing.JFrame.processWindowEvent(Unknown Source)
        at java.awt.Window.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at gov.usgs.volcanoes.core.ui.GlobalKeyManager.dispatchEvent(GlobalKeyManager.java:82)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by dnorgaard-usgs** [comment]
Fixed in volcano-core 1.3.8 (gov/usgs/volcanoes/core/configfile/ConfigFile.java).  Version 2.6.4 of Swarm should contain this fix.

**Comment by dnorgaard-usgs** [comment]
Fixed in 2.7.0
