### ISSUE TITLE
Particle Motion Analysis

### ISSUE THREAD

**Issue by dnorgaard-usgs** [usgs/swarm#84]
VDAP Geophysics team requests ability to perform particle motion analysis within Swarm.  Users should be able to select window and view the selected window within larger window, while simultaneously viewing the motion plot.  Users would also ideally be able to tell where the plot starts and ends.

**Comment by dnorgaard-usgs** [comment]
Initial particle motion plot capabilities released in version 2.6.3. (Look for the button next to spectrogram view in helicorder view.)  Some work still required based on original and subsequent request/feedback:

- Display wave view for each component.  Show zoomed in version for which the pm plot applies as well as zoomed out view with some indication of which part of the wave is being plotted in pm.
- Add label to the numbers next to the plot so users understand what it is. It is the extent of the plot. "xy lim" has been suggested.
- Add some indicator so users understand the coloring scheme of the plot.  Plot begins as red at start time and ends as blue at end time.
- Only Z, N, E components are plotted.  For example, it would not work on BHZ, BH1, and BH2.

**Comment by dnorgaard-usgs** [comment]
On Thu, Apr 27, 2017 at 11:18 AM, Norgaard, Diana <dnorgaard@usgs.gov> wrote:
Hi Carlos,

Thank you for the info and the corresponding data file.  The particle motion plot relies on knowing the SCNL for the data, and it appears that this information is not necessarily available when a data file is imported.  I will look into addressing this issue.

Diana

On Thu, Apr 27, 2017 at 10:48 AM, Carlos Andrés Laverde <claverde@sgc.gov.co> wrote:
Dear Diana,

Thanks for your reply.

These are the error messages:

-------
Exception in thread "Thread-130" java.lang.NullPointerException
        at gov.usgs.volcanoes.swarm.wave.AbstractWavePanel.plotParticleMotion(AbstractWavePanel.java:1107)
        at gov.usgs.volcanoes.swarm.wave.AbstractWavePanel.constructPlot(AbstractWavePanel.java:896)
        at gov.usgs.volcanoes.swarm.wave.AbstractWavePanel.access$000(AbstractWavePanel.java:48)
        at gov.usgs.volcanoes.swarm.wave.AbstractWavePanel$5.run(AbstractWavePanel.java:683)
        at gov.usgs.volcanoes.swarm.wave.AbstractWavePanel$6.construct(AbstractWavePanel.java:692)
        at gov.usgs.volcanoes.swarm.SwingWorker$2.run(SwingWorker.java:108)
        at java.lang.Thread.run(Unknown Source)
-------

I´m attaching a sample signal in Matlab readable text file format.

Thank for your kind support and best regards,

Carlos Andrés

**Comment by dnorgaard-usgs** [comment]
Added to 2.7.0:
- Add label to the numbers next to the plot so users understand what it is. It is the extent of the plot. "xy lim" has been suggested.
- Add some indicator so users understand the coloring scheme of the plot. Plot begins as red at start time and ends as blue at end time.
- Error handling for issue Carlos reported.  Better support for Matlab files will likely go in next release.

My understanding from feedback is that the initial capabilities presented is a start.  There is a desire to be able to view the wave form for each channel alongside the particle motion plot, but is not as high of a priority.  This ticket will be closed and a separate one will be opened for this feature.
